version: "3"
networks:
  geoserver_network:
    driver: bridge
services:
  geoserver:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GEOSERVER_WEBAPP_SRC: "https://sourceforge.net/projects/geoserver/files/GeoServer/2.27.1/geoserver-2.27.1-war.zip/download"
    deploy:
      replicas: 1
    ports:
      - 8080
    networks:
      - geoserver_network
  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - geoserver
    networks:
      - geoserver_network
