version: "3"
networks:
  geoserver_network:
    driver: bridge
services:
  geoserver:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GEOSERVER_WEBAPP_SRC: "https://build.geoserver.org/geoserver/main/geoserver-main-latest-war.zip"
    deploy:
      replicas: 1
    ports:
      - 8080
    networks:
      - geoserver_network
  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - geoserver
    networks:
      - geoserver_network
